### ISSUE TITLE
Unable to install ROCm on 24.04

### ISSUE THREAD

**Issue by mKenfenheuer** [nktice/AMD-AI#3]
Followed your steps exactly to "More AMD ROCm related packages", everything went fine until 
`sudo apt install -y rocm-dev rocm-libs rocm-hip-sdk rocm-dkms rocm-libs`

It cannot find the following packages:

```
 hipsolver : Depends on: libcholmod3 but is not installable
             Depends on: libsuitesparseconfig5 but is not installable
 rocm-gdb : Depends on: libtinfo5 but is not installable
            Depends on: libncurses5 but is not installable

```

Any idea what I am missing?

**Comment by nktice** [comment]
Did you get this line? I realize now that it likely applies too... 
```bash 
sudo add-apt-repository -y -s deb http://security.ubuntu.com/ubuntu jammy main universe
```

**Comment by mKenfenheuer** [comment]
Worked, thanks!
