### ISSUE TITLE
Unable to build exllamav2

### ISSUE THREAD

**Issue by CubeTheThird** [nktice/AMD-AI#9]
When trying the instructions provided for exllamav2, I end up with this:

```
INFO: pip is looking at multiple versions of exllamav2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement ninja (from exllamav2) (from versions: none)
ERROR: No matching distribution found for ninja
```

I did make sure to do the `conda install ninja` for what it's worth. Perhaps I missed something?

**Comment by CubeTheThird** [comment]
Ah, seems I'm an idiot. Needed to install the requirements.txt in the exllamav2 repo. Might want to add that in the script.

**Comment by nktice** [comment]
Thanks for the heads up... I have added those details, so they are there now.
